### ISSUE TITLE
AttributeError: module 'gmaps' has no attribute 'plot_markers'

### ISSUE THREAD

**Issue by Michael-E-Rose** [tcassou/mapsplotlib#1]
Trying to replicate the example fails:

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmaps
>>> gmaps.__version__
'0.6.1'
>>> import pandas as pd
>>> pd.__version__
'0.20.3'

>>> latitude = [48.8733, 48.8728]
>>> longitude = [2.32403, 2.30491]
>>> color = ['orange', 'black']
>>> size = ['mid', 'mid']
>>> label = ['A', 'Z']
>>> df = pd.DataFrame({'latitude': latitude, 'longitude': longitude, 'color': color, 'size': side, 'label': label})
>>> df
    color label  latitude  longitude size
0  orange     A   48.8733    2.32403  mid
1   black     Z   48.8728    2.30491  mid
>>> import gmaps
>>> 
>>> gmaps.plot_markers(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gmaps' has no attribute 'plot_markers'
```

**Comment by tcassou** [comment]
Hi @Michael-E-Rose, thanks for reporting!

The way `gmaps` is distributed right now (simple `git clone`) the package should not have any `__version__` attribute.
I just checked and there is a package with the same name on `pypi`, did you maybe install this one through `pip`? 

By just cloning the repo you should not have any issue, I just cloned it on a new machine and tried it successfully.
I'm going to add a `requirements.txt` though to make the install a bit smoother.

Let me know if you still experience issues,

Thomas

**Comment by Michael-E-Rose** [comment]
Wait, gmaps from pypi (https://pypi.python.org/pypi/gmaps) is not the same as the gmaps from this repo?

**Comment by tcassou** [comment]
That's correct. `gmaps` from `pypi` produces a interactive map for `Jupyter`, while this `gmaps` produces static plots in a similar way as `matplotlib`.
The same names are an unfortunate coincidence.
