### ISSUE TITLE
Unusable Map Results

### ISSUE THREAD

**Issue by oitsjustjose** [tcassou/mapsplotlib#11]
Using the variety of different plotting tools offered by your (very awesome, mind you) tool, I'm unable to see any details on the map whatsoever aside from the plots and very basic water features. Any idea what the cause may be? There's no output indicating that my inputs aren't correct.

![image](https://user-images.githubusercontent.com/3887324/40256101-0174fdac-5aaf-11e8-99f0-e758c3a23bdc.png)

**Comment by tcassou** [comment]
Hi @oitsjustjose,

Thanks for reporting! Could you maybe share some of the lat/long coordinates you're plotting, along with the method you're using, etc?
Just for me to be able to reproduce the output and see what could go wrong.

Thanks!

**Comment by oitsjustjose** [comment]
35.129513	85.236767
34.987145	85.287543
35.024158	85.246468
35.001344	85.352343
35.083343	85.323614
35.341032	85.129112
35.341032	85.129112
35.191175	85.242002
35.341032	85.129112

**Comment by tcassou** [comment]
Hi @oitsjustjose,
It seems that this area is not well documented by Google, or relatively desert.
You can double check [ on Google Maps](https://www.google.com/maps/place/35%C2%B007'46.3%22N+85%C2%B014'12.4%22E/@35.5325541,83.4847597,5.54z/data=!4m5!3m4!1s0x0:0x0!8m2!3d35.129513!4d85.236767), background maps in the package come directly from there.
This does not seem to be a bug, so I'll close the issue, feel free to reopen if needed!
