### ISSUE TITLE
Heatmap returns error: UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by ChakChak1234** [tcassou/mapsplotlib#12]
For some reason, using the `heatmap` function returns this error
'UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)' 
, when the function worked fine a few days ago.

After doing some investigating, I was able to figure out with what I believe may have been the issue:

The `GoogleStaticMapsAPI.map` function uses one's api key to call an image of the map, which returns the 403 error. I was able to side step this issue by customizing my own version of the `GoogleStaticMapsAPI.map` function without appending api key to the end of the url.

Is this issue happening to other people too? How can one sidestep this problem?

**Comment by tcassou** [comment]
Hi @ChakChak1234 
Thanks for reporting, I'll have a look!

**Comment by tcassou** [comment]
Hi @ChakChak1234 
I found out: this happens if you have not configured your billing details (note that for personal and reasonable usage you won't pay anything, the first 300$ are free in your first year).
When disabling payment, I get the same forbidden error; when reenabling it everything works fine.

I'll fix the exception, and will add it to the README, thanks again for reporting!

**Comment by ChakChak1234** [comment]
Hey @tcassou 

Thanks for the quick response. I figured that that was an important factor to issues #12 and #13, I just didn't know how to phrase it as "You need to pay."

Does this mean that the `requests.get()` function won't return the api_key now?

**Comment by tcassou** [comment]
Not sure I get your question on `requests.get()`? The API key has to be passed to the url.

If you use an API key, it looks like your account now has to be configured with billing details (this has probably been enforced very recently, it used to be ok).
It looks like you can still call the API and get results without using the key, and I suspect this will not last for too long..! 

I'll try to find more context, but there's a chance that "we have to pay" indeed... At least the first 300$ are free...

**Comment by tcassou** [comment]
From [this page](https://cloud.google.com/free/) it seems that the Static Maps API is not part of the free products (with quotas)...

**Comment by ChakChak1234** [comment]
Ahh, I suspect as much. :(

I sorta went ahead and wrote my own version of `mplt.heatmap()` that builds
on some of your various functions. Below is the current status - notice how
the borders don't align...yet. :(
If you need this code, I'll happily provide it. Happy to contribute to the
community and be noted for it!

In the worst case scenario, what would happen to mapsplotlib once google
maps static api finalizes its conditions and policies?
[image: download (2).png]

**Comment by tcassou** [comment]
Simple fix that works for now: allowing not to set the API key. Although I'm sure some constraints apply, and the number of requests will be limited. This is also how you side stepped the issue right? If not happy to see how you did it!
I can release an update soon.

This package can still be used of course despite the pricing change, although it will loose some of its interest if you have to start paying... Then I guess I'll take a look at Open Street Maps for example.

**Comment by ChakChak1234** [comment]
Yeah, I side-stepped the issue by not including the api_key value into the url string to call the static map.

In my case, my issue was for `mplt.heatmap()`, so I broke apart the function into to img, pixel portion and the plotting portion. The code for the pixel portion still works, but I wrote this to obtain the img. Nothing too fancy. I should also note that because I had to call specific functions individually, I had to import specific portions of the mapsplotlib library.

```
def get_img(country, zoom, size, scale, maptype):
    # url variable store url
    url  = 'https://maps.googleapis.com/maps/api/staticmap?'
    url += 'center={}&'.format(country)
    url += 'zoom={}&'.format(zoom)
    url += 'scale={}&'.format(scale)
    url += 'size={}x{}&'.format(size, size)
    url += 'maptype={}&'.format(maptype)
    
    r = requests.get(url)
    img = Image.open(StringIO((r.content)))
    
    return img
```

**Comment by tcassou** [comment]
This is very close to what I modified in [this commit](https://github.com/tcassou/mapsplotlib/commit/10a6ed721f8a082e454246c7d6845279b19bb0af), directly in the `GoogleStaticMapsAPI` class. I'll release an updated version in a few minutes, let me know if you still encounter issues.

**Comment by tcassou** [comment]
https://pypi.org/project/mapsplotlib/1.1.2/

**Comment by tcassou** [comment]
@ChakChak1234 does the new version work for you? Can I close this issue?
Thanks!

**Comment by ChakChak1234** [comment]
The issue was fixed [at least until google static map api finalizes their conditions and policies]. Thanks so much!
