### ISSUE TITLE
Image positioning and zooming

### ISSUE THREAD

**Issue by alex-kravets** [tcassou/mapsplotlib#15]
Hi,

Is there any way to manually specify:

- coordinates for that will be located at the center of the image,
- zooming ratio,
-  or maybe ROI?

For example, for the attached image it seems like a good idea to move the center higher to the North and zoom in.

![download](https://user-images.githubusercontent.com/42229431/44417288-47ee9000-a59f-11e8-9210-b2b08e8348e0.png)

And, by the way, thanks for the very cool tool!

**Comment by tcassou** [comment]
Hi @alex-kravets, thanks for reporting!
In theory the map should be centered around your dataset, with just the right level of zoom (I agree it does not look right here). So I'm curious to dig a little bit deeper here, can you maybe share the dataset you used for this scatter plot?
Thanks a lot!

**Comment by tcassou** [comment]
Hi @alex-kravets 
Without the data to reproduce the plot (at least lat/lon of all markers) I'm afraid I won't be able to support.
So I'll close this issue for now, and feel free to reopen it if you're still facing challenges and are open to share your input.
