### ISSUE TITLE
Heatmap colours are very dim

### ISSUE THREAD

**Issue by omerfarukeker** [tcassou/mapsplotlib#17]
Hello Thomas,

Thanks for the great package. It helps me a lot. I just want to know whether I can increase the colour intensities in the heatmap function. I could not find a parameter to do that. Appreciate your help. Cheers!

**Comment by tcassou** [comment]
Hi @omerfarukeker, thanks for raising this! 
At the moment the `alpha` parameter is hardcoded here and there (with relatively high transparency), and it would be easy to make it an argument with default value.
Would that help?
Thomas

**Comment by tcassou** [comment]
Hi @omerfarukeker 
I just released [1.1.3](https://pypi.org/project/mapsplotlib/1.1.3/) with a new `alpha` parameter in most plot functions, to allow for more contrasted colours. 
Let me know if you face any issues!
