### ISSUE TITLE
Polyline?

### ISSUE THREAD

**Issue by ZephD** [tcassou/mapsplotlib#18]
Heya,
You have polygons, but I was surprised to see you don't support Polylines.
Would this be a feature worth adding?
Thanks.

**Comment by tcassou** [comment]
Hi @ZephD 
Thanks for suggesting, this sounds like a good (and simple) feature to add! 
I'll take a look as soon as possible,
Thomas

**Comment by tcassou** [comment]
Is this more or less what you had in mind @ZephD ?
![image](https://user-images.githubusercontent.com/8159430/59533512-fe837e80-8eeb-11e9-8d0c-7202441fbadc.png)

**Comment by tcassou** [comment]
I have released [1.2.0](https://pypi.org/project/mapsplotlib/1.2.0/) for now with the `polyline` method, happy to tweak it if needed based on your feedback.
I'll close this for now, feel free to reopen.
