### ISSUE TITLE
Set upper limit in `get_zoom` function.

### ISSUE THREAD

**Issue by rudolfbyker** [tcassou/mapsplotlib#6]
If the list of latitudes and longitudes passed to `get_zoom` has only one point, or they are all at the same point, the return value of this function goes to infinity, causing `OverflowError: cannot convert float infinity to integer`. This should be caught or prevented, and a maximum zoom value returned. OR: A more descriptive error should be raised.

**Comment by rudolfbyker** [comment]
Basically you can just do
```py
if amplitudes.max() == 0:
  return MAX_ZOOM
```

**Comment by tcassou** [comment]
Hi @rudolfbyker, I'll incorporate these changes, thanks a lot for reporting again!

**Comment by tcassou** [comment]
@rudolfbyker in the end I used a default zoom instead of the maximum, as I find the map friendlier (you can still understand what you're looking at).
Thanks!
