### ISSUE TITLE
unable to import mapsplotlib

### ISSUE THREAD

**Issue by adamchui** [tcassou/mapsplotlib#8]
While I was importing the library

from mapsplotlib import mapsplot as mplt

It prompts me the error

  File "C:\ProgramData\Anaconda3\lib\site-packages\mapsplotlib\mapsplot.py", line 213
    print '[WARN] Cannot draw polygon for cluster {} - only {} samples.'.format(c, in_polygon.sum())

SyntaxError: invalid syntax

Please advise what to do

**Comment by tcassou** [comment]
Hi @adamchui, thanks for reporting!
What version of python are you using? Looks like a python3 compatibility issue (since `print`becomes a function), so I should be able to provide a fix!
Let me know, thanks!

**Comment by adamchui** [comment]
Yes, I am using python 3.6, thanks!

**Comment by mohsinkerai** [comment]
Same problem here, using python 3.6, any quickfix here?

**Comment by tcassou** [comment]
Yup, working on it today, I'll keep you posted!

**Comment by tcassou** [comment]
Hi @adamchui & @mohsinkerai,

I provided a fix, and could use the package successfully with `python3.6`, it should work now!
I uploaded a [new version (1.1.0) to pypi](https://pypi.python.org/pypi/mapsplotlib/1.1.0), let me know if you can use the package once you've upgraded it.

Thomas
